import type { Metadata } from 'next'
import '../ui/globals.css'
import { inter } from '../ui/fonts'
import { Section } from '../ui/dashboard/Section'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={`min-h-screen flex flex-col ${inter.className}`}>
      <header className='h-[100px] min-w-screen bg-[#ffab03]'>
      </header>

      <div className='flex flex-row'>
        <Section></Section>

        {children}
      </div>

    </div>
  )
}